;; Remove the startup screen and scratch message
(setq inhibit-startup-message t)
(setq initial-scratch-message nil)

;; Remove the menu bar
(menu-bar-mode -1)

;; Enable MELPA for package management
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

;; Install use-package if not installed
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)

;; Set initial mode to text-mode
(setq initial-major-mode 'text-mode)

;; Enable drag-stuff package
(use-package drag-stuff
  :ensure t
  :config
  (drag-stuff-global-mode 1)
  ;; Set keyboard shortcuts for drag-stuff
  (global-set-key (kbd "ESC <down>") 'drag-stuff-down)
  (global-set-key (kbd "ESC <up>") 'drag-stuff-up)
  (global-set-key (kbd "ESC <left>") 'drag-stuff-left)
  (global-set-key (kbd "ESC <right>") 'drag-stuff-right))

;; Custom-set variables and faces generated by Emacs
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   '("c7fd1708e08544d1df2cba59b85bd25263180b19b287489d4f17b9118487e718" default))
 '(package-selected-packages '(monokai-theme company drag-stuff)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(load-theme 'monokai t)

(global-unset-key (kbd "<left>"))
(global-unset-key (kbd "<right>"))
(global-unset-key (kbd "<up>"))
(global-unset-key (kbd "<down>"))
(global-unset-key (kbd "<C-left>"))
(global-unset-key (kbd "<C-right>"))
(global-unset-key (kbd "<C-up>"))
(global-unset-key (kbd "<C-down>"))
(global-unset-key (kbd "<M-left>"))
(global-unset-key (kbd "<M-right>"))
(global-unset-key (kbd "<M-up>"))
(global-unset-key (kbd "<M-down>"))

(setq backup-directory-alist '(("." . "~/.emacs-saves")))                                
(setq auto-save-file-name-transforms '((".*" "~/.emacs-saves" t)))

(setq lock-file-name-transforms `((".*" "~/.emacs-lockfiles/" t)))
